### ISSUE TITLE
Are AIS messages supported?

### ISSUE THREAD

**Issue by xslim** [ttlappalainen/NMEA0183#1]
According to `NMEA0183Msg.h` `MAX_NMEA0183_MSG_LEN` cannot contain multi messages.

Does this mean proper handling of AIS messages are not supported yet in this library?

I'm working on multiplexing NMEA from different sources and send it out to WiFI, so currently I don't need to parse AIS, just properly know if the message is fully red.

**Comment by ttlappalainen** [comment]
Hi,

I took MAX_NMEA0183_MSG_LEN from some standard. How multi messages are handled on NMEA0183?

**Comment by xslim** [comment]
Actually, one of the forks of your project fixes handling AIS - https://github.com/KimBP/NMEA0183

Could be nice if you guys will merge.

**Comment by ttlappalainen** [comment]
Yes I wonder why he has not asked "Pull request". I am not yet so familiar with GitHub, so can I ask "Push request"?

**Comment by xslim** [comment]
Yes, you can do it. I just did that.
