### ISSUE TITLE
Not sure that it's an issue, but I ask

### ISSUE THREAD

**Issue by hugorobi** [ttlappalainen/NMEA0183#16]
Timo,

When I use "PrintNMEA" example from NMEA0183 library, with Chrome NMEA Simulator (https://chrome.google.com/webstore/detail/nmea-simulator/dfhcgoinjchfcfnnkecjpjcnknlipcll/related), sentences are displayed successfully.

If I change the source from Chrome Simulator to the RTL_AIS receiver (https://github.com/dgiardini/rtl-ais), "PrintNMEA" appear to be unable to parse the sentences (none are displayed).

The main difference between sentences appear to be :
"!AIDVO" for sentences that work fine (Chrome NMEA Simulator). First image with 2 sentences
"!AIVDM" for sentences that are not displayed (RTL_AIS). Second image with 9 sentences

Any idea about the source of the problem ? 

Thank you !

![Chrome NMEA Simulator](https://user-images.githubusercontent.com/46845148/74992727-f387d300-5416-11ea-8689-152aa84f65f0.PNG)

![RTL_AIS](https://user-images.githubusercontent.com/46845148/74992734-faaee100-5416-11ea-9f62-d176db290cfd.png)

**Comment by ttlappalainen** [comment]
Can not see any reason on library for that. Library simply reads data between $ or ! to * and separates fields with , . So on that point it does not care about sender or field content. Can you check that you feed data with right baudrates etc.

**Comment by hugorobi** [comment]
... 😔🙄

Sorry, just after click "Comment", I remember that one thing was not tested... Serial communication... 

You're right...Serial configuration problem. Wrong serial port selected on Raspberry.

Again, sorry for that and thank you for your great job !

Hugo

**Comment by hugorobi** [comment]
.
