### ISSUE TITLE
ParseDPT, DBS or DBK missing

### ISSUE THREAD

**Issue by mjsneijders** [ttlappalainen/NMEA0183#30]
seems i cant find the parser for depth,  did it go missing somewhere, or was it never implemented?

**Comment by ttlappalainen** [comment]
Never implemented.

**Comment by mjsneijders** [comment]
i guess i have a task then... ;-)

**Comment by yiannis33** [comment]
Just implemented DBT, DPT,  VLW and VHW to use the Airmar DST-800 with NMEA0183 in the STNG Network.
If you need the code...
