### ISSUE TITLE
Leading zeros missing in RMC 

### ISSUE THREAD

**Issue by dagnall53** [ttlappalainen/NMEA0183#58]
I am seeing is what I think is incorrect Longitude - missing leading zero - ..
(possibly also a potential for incorrect Latitude) 
I have just updated to latest versions of your libraries (and in doing so found errors in the RZ AIS examples I will report to him) 

I have noted two (closed) issues regarding leading zeros but they are not related to this - or have been superseded?. 

DESCRIPTION: 
I have GPS sends 0183 that is converted to N2000 (your code)  $GPRMC,161659.00,A,5047.44532,N,00100.10202,W,0.046,,100724,,,A*6E
a second device accepts this N2000 data but gives this translation back 
$GPRMC,161659.00,A,5047.445,N,100.102,W,0.0,0.0,100724,,*2C

This is confusing an 0183 app later that reports the longitude as 100 degrees and 0 minutes! (I will get more data and update!). It is possible to argue that they are not interpreting "dddmm.xx" correctly, but it would be better if leading zeros were present. 

I suspect the issue is in NMEA0183SetRMC. where we have
` if ( !NMEA0183Msg.AddLatitudeField(Latitude) ) return false;
  if ( !NMEA0183Msg.AddLongitudeField(Longitude) ) return false;`  
  
I cannot see any code that currently attempts to add any leading zero(s). (longitude or latitude?) if degrees value is < 100? (or double zeros if less than 10).
Your opinion would be appreciated!!

Dagnall

**Comment by ttlappalainen** [comment]
Would
```
if ( !NMEA0183Msg.AddLatitudeField(Latitude,"08.3f") ) return false; 
if ( !NMEA0183Msg.AddLongitudeField(Longitude,"09.3f") ) return false;
```

or changing default format for bool AddLongitudeField(double Longitude, const char *Format="09.3f");
work?

**Comment by dagnall53** [comment]
Ha!!  ;-)   
I had just effectively done exactly that and compiled and it seems to work! 
But I modified the definitions in **NMEA0183Msg.h**
  
```
// Add Latitude field. Also E/W will be added. Latitude is in degrees. Negative value is W. E.g.
    // AddLatitudeField(-5.2345); -> ,5.235,W
    bool AddLatitudeField(double Latitude, const char *Format="%08.3f");
    //original bool AddLatitudeField(double Latitude, const char *Format="%.3f");

```

```
   // Add Longitude field. Also N/S will be added. Longitude is in degrees. Negative value is S. E.g.
    // AddLongitudeField(-5.2345); -> ,514.070,S
    bool AddLongitudeField(double Longitude, const char *Format="%09.3f");
    //Original:  bool AddLongitudeField(double Longitude, const char *Format="%.3f");

```
Result:
`
$GPRMC,184345.00,A,5047.453,N,00100.094,W,0.4,0.0,100724,,*22
`
I was just logging on to Git hub to advise you!! but you got there first!

Have a great evening..
Dagnall

**Comment by dagnall53** [comment]
To close: the leading zero issue was (I believe) the root cause of this fault, where a Standard Horizon VHF was getting RMC from a (converted) N2000 Gnss (shown correctly in upper picture. 
Its arguable if the Standard Horizon should have interpreted the ddmm. as dddm. - which is what it did to give 120degrees! but having the leading zero always present to make dddmm. should prevent all arguments! 

![image](https://github.com/ttlappalainen/NMEA0183/assets/6950560/152a41ee-6c24-4c61-b7c1-9cee17066e3d)

**Comment by ttlappalainen** [comment]
I pushed the fix. Fixed also crossing comment.
