### ISSUE TITLE
Question: multiple instance support?

### ISSUE THREAD

**Issue by wjquigs11** [ttlappalainen/NMEA0183#65]
Does the 0183 library support multiple instances of the class?
I'm using a PICAN-M hat on ESP32 to translate N2K wind PGNs to NMEA0183 and sending them through the RS422 port to my Autohelm tiller pilot for "steer-to-wind" mode. I would like to connect another NMEA0183 device to another UART, if the library supports multiple instances.

**Comment by ttlappalainen** [comment]
It is real class and should work as many instances you like. Remember to call ParseMessages() for each object.

**Comment by wjquigs11** [comment]
Excellent, thank you. I am now parsing GPS/0183 from my old VHF on RS422 and RTK GPS/0183 on UART.
